/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bls_BLS */

#ifndef _Included_bls_BLS
#define _Included_bls_BLS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bls_BLS
 * Method:    initialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_bls_BLS_initialize
  (JNIEnv *, jobject, jint);

/*
 * Class:     bls_BLS
 * Method:    getOrderBytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_bls_BLS_getOrderBytes
  (JNIEnv *, jobject);

/*
 * Class:     bls_BLS
 * Method:    computeKeyPair
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_bls_BLS_computeKeyPair
  (JNIEnv *, jobject);

/*
 * Class:     bls_BLS
 * Method:    computePublicKey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bls_BLS_computePublicKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bls_BLS
 * Method:    computeSignature
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bls_BLS_computeSignature
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     bls_BLS
 * Method:    computeVerification
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_bls_BLS_computeVerification
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     bls_BLS
 * Method:    interpolatePartialSignatures
 * Signature: ([[[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bls_BLS_interpolatePartialSignatures
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     bls_BLS
 * Method:    interpolatePartialPublicKeys
 * Signature: ([[[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_bls_BLS_interpolatePartialPublicKeys
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
